keys:
  - &users:
    - &niko age1d4ql06gfsrg3t53f68e9harn9llc4v7zl8lmequ656q6cn908uwqcr4jh9
  - &configurations:
    - &laptop-fw13 age1l59qjklfyzsg3uecjth6ltzzfs89gaffefx820w72j9cvaddsqmsrsxpwm
    # - &ms-01 age1lnpctyvkwczqwgqs4dsm3sldty8h2qgu800xj8xha9v3h6wdx4ms8xzlfg
    - &vm-edge age1argh5knhkvgrwew4e5xtaphcjmk4fv6ydxyzdtcwfgshyzxv7e5s2tcleu 
    - &vm-core age1cp5vy0zp30w5573328wn057uj3asucw9rgjdqcpjzgadcnch3dsq7nhvf5
creation_rules:
  - path_regex: users/niko/secrets.yaml$
    key_groups:
    - age:
      - *niko
      - *laptop-fw13
  - path_regex: configurations/laptop-fw13/secrets.yaml$
    key_groups:
    - age:
      - *niko
      - *laptop-fw13
  # - path_regex: configurations/ms-01/secrets.yaml$
  #   key_groups:
  #   - age:
  #     - *niko
  #     - *ms-01
  - path_regex: configurations/vm-edge/secrets.yaml$
    key_groups:
    - age:
      - *niko
      - *vm-edge
  - path_regex: configurations/vm-core/secrets.yaml$
    key_groups:
    - age:
      - *niko
      - *vm-core
